### ISSUE TITLE
How do you fetch USD Values

### ISSUE THREAD

**Issue by kroil** [philipperemy/bitmex-liquidations#4]
Hello,

Thank you for sharing your liquidation bot.

I was wondering, how are you able to convert a contract size value to USD, aside from XBT?

I have seen, that you used:

`usd_value = price * qty if not symbol.startswith('XBT') else qty`

But I think that is not all. Since if I cross check that formula with your website's values they are all different.

Looking at for example [ETHUSD](https://www.bitmex.com/app/contract/ETHUSD) each contract is worth 0.001 mXBT per $1 price, currently 0.00121444 XBT. A simple `price * qty` should not be enough.

Another not clear example would be:
![img](https://i.imgur.com/28dEgjG.png)

If I do `price * qty` it would result in `63` and not `2`, as shown in the screenshot. I might be missing something here, thats why I thought to shoot you a message.

Aside from that I have also noticed that the usd_value is different from the GitHub's version vs the rek.to.

GitHub Bot:
![img](https://i.imgur.com/n0UwvRD.png)

Website:
![img](https://i.imgur.com/8FAEuIF.png)

> GH Bot has USD = 1,935. Website = 68.

When looking at bitmex.com the order value of 7,000 XRP is also a complete different one:

![img](https://i.imgur.com/orWPUWP.png)

Thanks for enlighten me on this.

**Comment by kroil** [comment]
After looking more into this I think your calculations are wrong and you did not respect the vale per contract size for coins aside from XBT.

**Comment by philipperemy** [comment]
Right ETHUSD is a quanto contract so the XBTUSD formula will be incorrect.
Can you update it if you have time?
